export const EASY_ROWS = 4;
export const EASY_COLS = 8;
export const HARD_ROWS = 8;
export const HARD_COLS = 16;
export const LETTER_VALUE = 'ABCDEFGHIJKLMNOPQRSTUVWXYZ!@#$%^&*()_+-=[]{}|;:,.<>?';
export const SYMBOL_VALUE = '!@#$%^&*()_+-=[]{}|;:,.<>?';
export const ICON_NAMES: string[] = [
  'home',
  'search',
  'user',
  'settings',
  'mail',
  'bell',
  'calendar',
  'camera',
  'heart',
  'star',
  'trash',
  'edit',
  'bookmark',
  'link',
  'share',
  'download',
  'upload',
  'refresh',
  'lock',
  'unlock',
  'check',
  'paperclip',
  'phone',
  'mic',
  'wifi',
  'battery',
  'bluetooth',
  'map',
  'compass',
  'cloud',
  'umbrella',
  'moon',
  'sun',
  'clock',
  'flag',
  'target',
  'zap',
  'coffee',
  'music',
  'film',
  'archive',
  'truck',
  'package',
  'gift',
  'cpu',
  'server',
  'database',
  'printer',
  'tv',
  'zoomIn',
  'zoomOut',
  'airplay',
  'cast',
  'award',
  'feather',
  'github',
  'gitlab',
  'codepen',
  'codesandbox',
  'terminal',
  'code',
];

export enum GAME_TOPIC {
  LETTER = 'letter',
  SYMBOL = 'symbol',
}
export enum GAME_LEVEL {
  EASY = 'easy',
  HARD = 'hard',
}
